# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import messages as msgs


class WorkerStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ping = channel.unary_unary(
        '/Worker/ping',
        request_serializer=msgs.VersionInfo.SerializeToString,
        response_deserializer=msgs.VersionInfo.FromString,
        )
    self.suggest_peers = channel.unary_unary(
        '/Worker/suggest_peers',
        request_serializer=msgs.PeersList.SerializeToString,
        response_deserializer=msgs.PeersList.FromString,
        )
    self.cognite_batch = channel.unary_unary(
        '/Worker/cognite_batch',
        request_serializer=msgs.CognitionRequest.SerializeToString,
        response_deserializer=msgs.CognitionResponse.FromString,
        )
    self.batch_status = channel.unary_unary(
        '/Worker/batch_status',
        request_serializer=msgs.BatchRequest.SerializeToString,
        response_deserializer=msgs.BatchStatus.FromString,
        )


class WorkerServicer(object):

  def ping(self, request, context):
    """ping accepts masternode version number and returns worker version number
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def suggest_peers(self, request, context):
    """Asks for peer worker suggestions for a given known list of peers
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def cognite_batch(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def batch_status(self, request, context):
    """batch_status accepts task_id returned in CognitionRequest structure
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WorkerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ping': grpc.unary_unary_rpc_method_handler(
          servicer.ping,
          request_deserializer=msgs.VersionInfo.FromString,
          response_serializer=msgs.VersionInfo.SerializeToString,
      ),
      'suggest_peers': grpc.unary_unary_rpc_method_handler(
          servicer.suggest_peers,
          request_deserializer=msgs.PeersList.FromString,
          response_serializer=msgs.PeersList.SerializeToString,
      ),
      'cognite_batch': grpc.unary_unary_rpc_method_handler(
          servicer.cognite_batch,
          request_deserializer=msgs.CognitionRequest.FromString,
          response_serializer=msgs.CognitionResponse.SerializeToString,
      ),
      'batch_status': grpc.unary_unary_rpc_method_handler(
          servicer.batch_status,
          request_deserializer=msgs.BatchRequest.FromString,
          response_serializer=msgs.BatchStatus.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Worker', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class MasternodeStub(object):

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.pong = channel.unary_unary(
        '/Masternode/pong',
        request_serializer=msgs.VersionInfo.SerializeToString,
        response_deserializer=msgs.VersionInfo.FromString,
        )
    self.suggest_peers = channel.unary_unary(
        '/Masternode/suggest_peers',
        request_serializer=msgs.PeersList.SerializeToString,
        response_deserializer=msgs.PeersList.FromString,
        )
    self.batch_completed = channel.unary_unary(
        '/Masternode/batch_completed',
        request_serializer=msgs.CognitionResult.SerializeToString,
        response_deserializer=msgs.CognitionStatus.FromString,
        )


class MasternodeServicer(object):

  def pong(self, request, context):
    """pong accepts masternode version number and returns worker version number
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def suggest_peers(self, request, context):
    """Asks for peer masternode suggestions for a given known list of peers
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def batch_completed(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MasternodeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'pong': grpc.unary_unary_rpc_method_handler(
          servicer.pong,
          request_deserializer=msgs.VersionInfo.FromString,
          response_serializer=msgs.VersionInfo.SerializeToString,
      ),
      'suggest_peers': grpc.unary_unary_rpc_method_handler(
          servicer.suggest_peers,
          request_deserializer=msgs.PeersList.FromString,
          response_serializer=msgs.PeersList.SerializeToString,
      ),
      'batch_completed': grpc.unary_unary_rpc_method_handler(
          servicer.batch_completed,
          request_deserializer=msgs.CognitionResult.FromString,
          response_serializer=msgs.CognitionStatus.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Masternode', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
